# -*- coding: utf-8 -*-
"""Pro 106.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2QyORAN3I_XRgRhjoVUXTv5oA3YPsKm
"""

from google.colab import files
data_to_load = files.upload()

import csv
import numpy as np
import pandas as pd
import plotly.express as px

def getDataSource(data_path):
    Ice_cream_sales = []
    Temperature = []
    with open(data_path) as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            Ice_cream_sales.append(float(row["Ice-cream Sales( ₹ )"]))
            Temperature.append(float(row["Temperature"]))

    return {"x" : Ice_cream_sales, "y": Temperature}

def findCorrelation(datasource):
    correlation = np.corrcoef(datasource["x"], datasource["y"])
    print("Correlation between Sales of Softdrinks with temp :-  \n--->",correlation[0,1])

def plotFigure(data_path):
  df = pd.read_csv("Ice Cream Sales.csv")
  fig = px.scatter(df, x="Ice-cream Sales( ₹ )", y="Temperature")
  fig.show()

def setup():
    data_path  = "Ice Cream Sales.csv"

    datasource = getDataSource(data_path)
    findCorrelation(datasource)
    plotFigure(data_path)

setup()